name: Black Formatter

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # use black github action see https://black.readthedocs.io/en/stable/integrations/github_actions.html
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "lmod examples"

      - name: Check imports with pyflakes
        run: |
          pip install pyflakes
          pyflakes lmod

