name: regressiontest

on:
  pull_request:
    branches: [ master ]

jobs:

  regression_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run lmodule regresison test for python version - ${{ matrix.python-version }}
      run: |
        LMOD_VERSION=7.8.2
        sh scripts/install_lmod.sh $LMOD_VERSION
        source /opt/apps/lmod/lmod/init/profile
        pip install -r docs/requirements.txt
        module --version
        module av
        coverage run -m pytest -vra tests/
        coverage report -m
        coverage xml        

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
        files: ./coverage.xml