name: Check URLs

on: [push, pull_request]

jobs:
  urlcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.0.33
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .rst,.py

        # Choose whether to include file with no URLs in the prints.
        print_all: false

        # How many times to retry a failed request (defaults to 1)
        retry_count: 3
